- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs-horizon
      - openstack-python-jobs-horizon
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - manila-ui-dsvm:
            voting: false
        - manila-ui-integration-tests:
            voting: false
- job:
    name: manila-ui-dsvm
    parent: legacy-dsvm-base
    run: playbooks/legacy/manila-ui-dsvm/run.yaml
    post-run: playbooks/legacy/manila-ui-dsvm/post.yaml
    timeout: 6000
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-ui
      - openstack/python-manilaclient
      - openstack/manila-tempest-plugin

- job:
    name: manila-ui-integration-tests
    parent: horizon-integration-tests
    required-projects:
      - name: openstack/horizon
      - name: openstack/manila
      - name: openstack/python-manilaclient
      - name: openstack/manila-ui
      - name: openstack/manila-tempest-plugin
    roles:
      - zuul: openstack-infra/devstack
      - zuul: openstack/horizon
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        manila: https://opendev.org/openstack/manila
        manila-ui: https://opendev.org/openstack/manila-ui
      devstack_services:
        horizon: true
      tox_envlist: integration

